name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: flutter_clock_helper
  cupertino_icons: ^0.1.2
  provider:
  flutter_bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/nixies/000.png
    - assets/nixies/001.png
    - assets/nixies/002.png
    - assets/nixies/003.png
    - assets/nixies/004.png
    - assets/nixies/005.png
    - assets/nixies/006.png
    - assets/nixies/007.png
    - assets/nixies/008.png
    - assets/nixies/009.png
    - assets/nixies/sep.png
    - assets/nixies/mask.png
    - assets/nixies/blinker.gif
    - assets/bgrounds/simplebg.png
